server:
  port: 8088
  servlet:
    session:
      timeout: 3600
spring:
  gson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://120.46.151.166:5432/zhsx
    username: lisang
    password: "00000..."
  data:
    solr:
      host: http://120.46.151.166:8983/solr/tour
mybatis:
  type-aliases-package: com.xinnn.tour.pojo
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml
pagehelper:
  helper-dialect: postgresql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql
